import Css from './Css';
import Html from './Html';
import JavaScript from './JavaScriptIndex';
import JavaScriptSlider from './JavaScriptSlider';
import JavaScriptPlayground from './JavaScriptPlayground';
import JavaScriptChosen from './JavaScriptChosen';
import SrcScreenIndex from './SrcScreenIndex';
import ScreensChoices from './ScreensChoices';
import ScreenChanges from './ScreensChanges';
import ScreensChanges2 from './ScreensChanges2';
import ScreensChanges3 from './ScreensChanges3';
export default [ Html, Css, JavaScript, JavaScriptSlider, JavaScriptPlayground, JavaScriptChosen, SrcScreenIndex, ScreensChoices, ScreenChanges, ScreensChanges2, ScreensChanges3 ];